services:

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - local
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  api1:
    image: wildemberg/api-payment-rinha:1.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - payment-processor
      - local
    environment:
      - PGHOST=db
      - PGUSER=db_user
      - PGPASSWORD=1234
      - PGDATABASE=payments_db
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=payments_db;Username=db_user;Password=1234
      - "URL_DEFAULT=http://payment-processor-default:8080"
      - "URL_FALLBACK=http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "75MB"
  
  api2:
    image: wildemberg/api-payment-rinha:1.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - payment-processor
      - local
    environment:
      - PGHOST=db
      - PGUSER=db_user
      - PGPASSWORD=1234
      - PGDATABASE=payments_db
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=payments_db;Username=db_user;Password=1234
      - "URL_DEFAULT=http://payment-processor-default:8080"
      - "URL_FALLBACK=http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "75MB"

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c autovacuum=off
      -c full_page_writes=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d payments_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "160MB"

networks:
  local:
    name: local
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data: